base_lr: 0.01
batch_size: 64
config: config/st_gcn/hanchoom/train.yaml
device:
- 0
eval_interval: 5
feeder: st_gcn.feeder.Feeder_hanchoom
ignore_weights: []
log_interval: 100
model: st_gcn.net.ST_GCN
model_args:
  channel: 3
  dropout: 0.3
  graph: st_gcn.graph.Hanchoom
  graph_args:
    labeling_mode: spatial
  mask_learning: true
  num_class: 8
  num_person: 1
  num_point: 18
  use_data_bn: true
  window_size: 100
nesterov: true
num_epoch: 100
num_worker: 128
optimizer: SGD
phase: train
print_log: true
save_interval: 5
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 30
- 40
- 50
test_batch_size: 64
test_feeder_args:
  data_path: ./data_hanchoom_final/hanchoom_val
  label_path: ./data_hanchoom_final/hanchoom_val_label.json
  mode: test
  window_size: 100
train_feeder_args:
  data_path: ./data_hanchoom_final/hanchoom_train
  label_path: ./data_hanchoom_final/hanchoom_train_label.json
  mode: train
  random_choose: true
  random_move: true
  window_size: 100
weight_decay: 0.001
weights: null
work_dir: ./work_dir/Hanchoom/ST_GCN/Final4
