
# model
model: st_gcn.net.st_gcn.Model
model_args:
  num_class: 8
  channel: 3
  window_size: 100
  num_person: 1
  num_point: 18
  dropout: 0
  graph: st_gcn.graph.hanchoom.Graph
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True


weights: ./work_dir/Hanchoom/ST_GCN/Final4/epoch30_model.pt