work_dir: ./work_dir/Hanchoom/ST_GCN/Final4

# feeder
feeder: st_gcn.feeder.feeder_hanchoom
train_feeder_args:
  mode: train
  data_path: ./data_hanchoom_final/hanchoom_train
  label_path : ./data_hanchoom_final/hanchoom_train_label.json
  random_choose: True
  random_move: True
  window_size: 100 
test_feeder_args:
  mode: test 
  data_path: ./data_hanchoom_final/hanchoom_val
  label_path : ./data_hanchoom_final/hanchoom_val_label.json
  window_size: 100

# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 8
  channel: 3
  window_size: 100
  num_person: 1
  num_point: 18
  dropout: 0.3
  graph: st_gcn.graph.Hanchoom
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True

#optim
weight_decay: 0.001
base_lr: 0.01
step: [20, 30, 40, 50]

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 100 
nesterov: True
save_interval: 5